#!/bin/sh

# Should be platform neutral - at least working on Linux and Windows
USER_NAME=`basename $HOME`

# Pass files on command line to the image via the FFFILES environment variable.
# Need to expand to the full path...
# Files must be in one of the mounted file systems with the -v option.
for file in $@; do
    COLLECT="${COLLECT} `readlink -f ${file}`"
done

# HHHOME is used to pass the HOME directory of the user running qgis
# and is used in "start.sh" to create the same user within the container.

# Users home is mounted as home
# --rm will remove the container as soon as it ends
docker run --rm \
    -i -t \
    -v ${HOME}:/home/${USER_NAME} \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e DISPLAY=unix$DISPLAY \
    -e HHHOME=${HOME} \
    -e FFFILES="${COLLECT}" \
    timcera/atom-editor:latest

